export { default as Home } from "./Home/Home.jsx"
export { default as About } from "./About/About.jsx"
export { default as Contact } from "./Contact/Contact.jsx"
export { default as Service } from "./Service/Service.jsx"
export { default as Explore } from "./Explore/Explore.jsx"
export { default as Trending } from "./Trending/Trending.jsx"
